[options]
addons_path = /mnt/extra-addons

admin_passwd = admin

db_host = dpg-d8eoievavr4c738vm570-a
db_port = 5432
db_user = inventory_viewer_db_user
db_password = t4gbXrKnKzxMX99y3VhGJNOMAzGUGrkX

db_name = inventory_viewer_db

http_port = 8069
